use_frameworks!

target 'ADFlowCalendarView_Example' do
  pod 'ADFlowCalendarView', :path => '../'

  target 'ADFlowCalendarView_Tests' do
    #inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
